# Generated by Django 5.1.5 on 2025-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Last Name"
            ),
        ),
    ]
