# Generated by Django 5.1.5 on 2025-03-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "permissions": [("view_all_users", "View all users")],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
