# Generated by Django 5.1.5 on 2025-02-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_sending",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date and time of first sending"
                    ),
                ),
                (
                    "end_sending",
                    models.DateTimeField(verbose_name="Date and time of ends sending"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Launched", "Launched"),
                            ("Completed", "Completed"),
                        ],
                        default="Created",
                        max_length=9,
                        verbose_name="Mailing status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailing",
                "verbose_name_plural": "Mailings",
                "ordering": ["first_sending"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Insert title of message",
                        max_length=300,
                        verbose_name="Title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Insert subject", verbose_name="Message"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Receiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Insert Name and surname of receiver",
                        max_length=300,
                        verbose_name="Name and surname",
                    ),
                ),
                (
                    "mail",
                    models.CharField(
                        help_text="Insert Email address of receiver",
                        max_length=300,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Insert description", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Receiver",
                "verbose_name_plural": "Receivers",
                "ordering": ["name", "mail"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.TimeField(auto_now=True, verbose_name="Time of the attempt"),
                ),
                (
                    "attempt_status",
                    models.CharField(
                        choices=[
                            ("Succeed", "Succeed"),
                            ("Not Succeed", "Not Succeed"),
                        ],
                        default="Succeed",
                        max_length=11,
                        verbose_name="Attempt status",
                    ),
                ),
                ("server_respond", models.TextField(verbose_name="Server respond")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing.mailing",
                        verbose_name="Mailing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attempt",
                "verbose_name_plural": "Attempts",
                "ordering": ["attempt_time"],
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="mailing.message",
                verbose_name="Message",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="receivers",
            field=models.ManyToManyField(
                help_text="Indicate receivers",
                related_name="mailings",
                to="mailing.receiver",
                verbose_name="receivers",
            ),
        ),
    ]
