# Generated by Django 5.1.5 on 2025-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiver",
            options={
                "ordering": ["name", "email"],
                "verbose_name": "Receiver",
                "verbose_name_plural": "Receivers",
            },
        ),
        migrations.RenameField(
            model_name="receiver",
            old_name="mail",
            new_name="email",
        ),
        migrations.AlterField(
            model_name="receiver",
            name="name",
            field=models.CharField(
                help_text="Insert Name and surname of receiver",
                max_length=300,
                verbose_name="Name",
            ),
        ),
    ]
