# Generated by Django 5.1.5 on 2025-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_receiver_options_rename_mail_receiver_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_chosen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receiver",
            name="receiver_chosen",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="description",
            field=models.TextField(help_text="Insert comment", verbose_name="Comment"),
        ),
    ]
