# Generated by Django 5.1.5 on 2025-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_message_message_chosen_receiver_receiver_chosen_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_sending",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date and time of ends sending"
            ),
        ),
    ]
