# Generated by Django 5.1.5 on 2025-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_end_sending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="attempt_status",
            field=models.CharField(
                choices=[("Succeed", "Succeed"), ("Not Succeed", "Not Succeed")],
                default=None,
                max_length=11,
                verbose_name="Attempt status",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="receivers",
            field=models.ManyToManyField(
                related_name="mailings", to="mailing.receiver", verbose_name="receivers"
            ),
        ),
    ]
