# Generated by Django 5.1.5 on 2025-02-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_attempt_attempt_status_alter_mailing_receivers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="attempt_status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("Succeed", "Succeed"),
                    ("Not Succeed", "Not Succeed"),
                ],
                default="Not Started",
                max_length=11,
                verbose_name="Attempt status",
            ),
        ),
    ]
