# Generated by Django 5.1.5 on 2025-03-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_attempt_attempt_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(
                help_text="Insert title of message",
                max_length=300,
                unique=True,
                verbose_name="Title",
            ),
        ),
    ]
