# Generated by Django 5.1.5 on 2025-03-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_message_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="mailing.message",
                unique=True,
                verbose_name="Message",
            ),
        ),
    ]
