# Generated by Django 5.1.5 on 2025-03-03 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0010_alter_mailing_mailing_sender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receiver",
            name="receiver_adder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adder",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
