# Generated by Django 5.1.5 on 2025-03-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0011_receiver_receiver_adder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_sending"],
                "permissions": [
                    ("view_all_mailings", "View all mailings"),
                    ("deactivate_mailings", "Deactivate mailings"),
                ],
                "verbose_name": "Mailing",
                "verbose_name_plural": "Mailings",
            },
        ),
    ]
