# Generated by Django 5.1.5 on 2025-03-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0012_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiver",
            options={
                "ordering": ["name", "email"],
                "permissions": [("view_all_receivers", "View all receivers")],
                "verbose_name": "Receiver",
                "verbose_name_plural": "Receivers",
            },
        ),
        migrations.RemoveField(
            model_name="receiver",
            name="receiver_chosen",
        ),
    ]
