# Generated by Django 5.1.5 on 2025-03-05 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0014_attempt_attempt_sender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="attempt_sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempt_sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
