# Generated by Django 5.1.5 on 2025-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0017_alter_message_message_sender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(
                help_text="Insert title of message",
                max_length=300,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="email",
            field=models.CharField(
                help_text="Insert Email address of receiver",
                max_length=300,
                verbose_name="Email",
            ),
        ),
    ]
