# Generated by Django 5.1.5 on 2025-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0018_alter_message_title_alter_receiver_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiver",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Insert comment",
                null=True,
                verbose_name="Comment",
            ),
        ),
    ]
