# Generated by Django 5.1.5 on 2025-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0019_alter_receiver_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Launched", "Launched"),
                    ("Completed", "Completed"),
                ],
                default="Draft",
                max_length=9,
                verbose_name="Mailing status",
            ),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
    ]
